<?php
declare(strict_types=1);
/**
 * Interface strings: list keys used in PHP (t('…')) and JS (MA.t('…')) that are missing from inc/lang/zh.php,
 * and write inc/lang/js_keys.php (the subset sent to the browser).
 *
 *   php tools/i18n_keys.php [--missing] [--json]
 */
if (PHP_SAPI !== 'cli') {
    exit;
}
$root = dirname(__DIR__);
$php = [];
$js = [];
$scan = function (string $file, string $re, array &$into) {
    $src = (string)file_get_contents($file);
    if (preg_match_all($re, $src, $m)) {
        foreach ($m[1] as $k) {
            $k = stripcslashes($k);
            $into[$k] = true;
        }
    }
};
$phpRe = "/\\bt\\(\\s*'((?:[^'\\\\]|\\\\.)*)'/";
foreach (array_merge(glob("$root/*.php") ?: [], glob("$root/inc/*.php") ?: []) as $f) {
    $scan($f, $phpRe, $php);
}
// constant tables translated at render time (MD_KINDS labels, AREAS, LEVELS, MD_LEVELS, lab groups, catalogue titles are separate)
require_once "$root/inc/markdown.php";
foreach (MD_KINDS as $k => [$label]) {
    $php[$label] = true;
    $php[ucfirst($k)] = true;
}
foreach (MD_LEVELS as $l) {
    $php[$l] = true;
}
$src = (string)file_get_contents("$root/inc/content.php");
if (preg_match_all("/'label' => '([^']+)', 'blurb' => '([^']+)'/", $src, $m)) {
    foreach ($m[1] as $i => $l) {
        $php[$l] = true;
        $php[$m[2][$i]] = true;
    }
}
foreach (['A1–A2', 'B1', 'B2', 'C1–C2'] as $l) {
    $php[$l] = true;
}
$jsRe = "/\\bMA\\.t\\(\\s*'((?:[^'\\\\]|\\\\.)*)'/";
$jsRe2 = '/\\bMA\\.t\\(\\s*"((?:[^"\\\\]|\\\\.)*)"/';
foreach (array_merge(glob("$root/assets/js/*.js") ?: [], glob("$root/assets/js/widgets/*.js") ?: []) as $f) {
    $scan($f, $jsRe, $js);
    $scan($f, $jsRe2, $js);
    // widget files that alias the translator: const T = MA.t  or  const T = (s, ...a) => MA.t(s, ...a)
    if (preg_match('/\bconst T = (MA\.t\b|\([^)]*\) => MA\.t\()/', (string)file_get_contents($f))) {
        $scan($f, "/\\bT\\(\\s*'((?:[^'\\\\]|\\\\.)*)'/", $js);
        $scan($f, '/\\bT\\(\\s*"((?:[^"\\\\]|\\\\.)*)"/', $js);
    }
}
unset($php[''], $js['']);
$zh = is_file("$root/inc/lang/zh.php") ? require "$root/inc/lang/zh.php" : [];
$all = $php + $js;
ksort($all);
$missing = array_values(array_filter(array_keys($all), fn($k) => !isset($zh[$k])));
file_put_contents("$root/inc/lang/js_keys.php", "<?php\n// generated by tools/i18n_keys.php — interface strings used by assets/js\nreturn " . var_export(array_keys($js), true) . ";\n");
if (in_array('--json', $argv, true)) {
    echo json_encode($missing, JSON_UNESCAPED_UNICODE | JSON_PRETTY_PRINT), "\n";
} elseif (in_array('--missing', $argv, true)) {
    foreach ($missing as $k) {
        echo $k, "\n";
    }
}
fwrite(STDERR, count($all) . ' keys (' . count($php) . ' PHP, ' . count($js) . ' JS), ' . count($missing) . " missing in zh.php\n");
