<?php
// List every UI string the site translates (dev tool): php tools/i18n_keys.php [--missing] [--js]
if (PHP_SAPI !== 'cli') { http_response_code(404); exit; }
require __DIR__ . '/../inc/bootstrap.php';

$root = dirname(__DIR__);
$keys = [];
$jsKeys = [];
$add = function (string $k, bool $js = false) use (&$keys, &$jsKeys) { $keys[$k] = true; if ($js) $jsKeys[$k] = true; };
$files = array_merge(glob("$root/*.php"), glob("$root/inc/*.php"));
foreach ($files as $f) {
    $src = file_get_contents($f);
    preg_match_all("/\\bt\\(\\s*'((?:[^'\\\\]|\\\\.)*)'/", $src, $m1);
    preg_match_all('/\\bt\\(\\s*"((?:[^"\\\\]|\\\\.)*)"/', $src, $m2);
    foreach ($m1[1] as $k) $add(stripcslashes(str_replace("\\'", "'", $k)));
    foreach ($m2[1] as $k) $add(stripcslashes($k));
    // Atlas.t('...') inside inline scripts
    preg_match_all("/Atlas\\.t\\(\\s*'((?:[^'\\\\]|\\\\.)*)'/", $src, $m3);
    preg_match_all("/Atlas\\.t\\(\\s*([a-z].*?\\?)\\s*'((?:[^'\\\\]|\\\\.)*)'\\s*:\\s*'((?:[^'\\\\]|\\\\.)*)'/", $src, $m4);
    foreach ($m3[1] as $k) $add($k, true);
    foreach ($m4[2] as $k) $add($k, true);
    foreach ($m4[3] as $k) $add($k, true);
}
foreach (glob("$root/assets/js/*.js") as $f) {
    $src = file_get_contents($f);
    preg_match_all("/A\\.t\\(\\s*'((?:[^'\\\\]|\\\\.)*)'/", $src, $m);
    foreach ($m[1] as $k) $add($k, true);
    preg_match_all("/A\\.t\\([^()]*?\\?\\s*'((?:[^'\\\\]|\\\\.)*)'\\s*:\\s*'((?:[^'\\\\]|\\\\.)*)'/", $src, $m);
    foreach ($m[1] as $k) $add($k, true);
    foreach ($m[2] as $k) $add($k, true);
    // labels translated through map(([v, l]) => [v, A.t(l)])
    preg_match_all("/\\[\\s*'[a-z]+'\\s*,\\s*'((?:[^'\\\\]|\\\\.)*)'\\s*\\]/", $src, $m);
    foreach ($m[1] as $k) if (preg_match('/[A-Z]/', $k)) $add($k, true);
    preg_match_all("/\\[\\s*'((?:Very high|Confident|Low|Very low)[^']*)'/", $src, $m);
    foreach ($m[1] as $k) $add($k, true);
}
// strings translated through constants and lookup tables
foreach (CATEGORIES as $c) { $add($c['label']); $add($c['blurb']); }
foreach (STATUSES as $s) { $add($s['label']); $add($s['long']); }
foreach (EVIDENCE as $e) $add($e);
foreach (EVENT_KINDS as $e) $add($e);
foreach (REG_STATUS as $e) $add($e);
foreach (['US', 'EU', 'UK', 'China', 'Japan', 'Russia', 'India', 'Canada', 'Australia', 'Brazil', 'WADA', 'South Korea', 'Mexico', 'Switzerland', 'Israel', 'Italy', 'Germany', 'France', 'Global', 'New Zealand', 'Argentina', 'Taiwan', 'Hong Kong', 'Singapore', 'Ukraine', 'Belarus', 'Kazakhstan', 'Turkey', 'Saudi Arabia', 'UAE', 'Egypt', 'South Africa'] as $r) $add('region:' . $r);
foreach (['Early phase 1', 'Phase 1', 'Phase 1/2', 'Phase 2', 'Phase 2/3', 'Phase 3', 'Phase 4', 'Not applicable', 'Observational',
          'Recruiting', 'Not yet recruiting', 'Active, not recruiting', 'Completed', 'Terminated', 'Withdrawn', 'Suspended', 'Enrolling by invitation',
          'Unknown status', 'Expanded access', 'No longer available', 'Approved for marketing', 'Temporarily unavailable', 'Withheld',
          'X-ray', 'Cryo-EM', 'NMR', 'Solid-state NMR', 'Cells/animals', 'Small human', 'Phase 1–2', 'Outcome trials',
          'Atlas', 'Timeline', 'World', 'Families', 'Structures', 'Compare', 'About',
          'Class', 'Status', 'Human evidence', 'Targets', 'Residues', 'Molecular weight', 'Half-life', 'Routes', 'Developer', 'First approval',
          'Wikipedia views, 12 months', 'PubMed papers', 'Registered trials', 'Net charge at pH 7.4', 'Isoelectric point',
          'Overview', 'History', 'Uses', 'Popularity', 'Research & trials', 'Chemistry', 'Safety', 'Regulation', 'Sources',
          'Peak level', 'Bioavailability', 'Metabolism', 'Excretion', 'Peptide', 'A chain', 'B chain',
          'Disulfide bridge', 'Lactam bridge', 'Thioether bridge', 'Other bridge'] as $k) $add($k);
foreach (['Switch to light theme', 'Switch to dark theme', '%d peptide', '%d peptides', '%d event', '%d events'] as $k) $add($k, true);

ksort($keys);
$dictFile = "$root/inc/lang/zh.php";
$dict = is_file($dictFile) ? require $dictFile : [];
if (in_array('--js', $argv, true)) {
    ksort($jsKeys);
    file_put_contents("$root/inc/lang/js_keys.php", "<?php\n// Generated by tools/i18n_keys.php --js: UI strings used by assets/js and inline scripts.\nreturn " . var_export(array_keys($jsKeys), true) . ";\n");
    echo count($jsKeys), " JS keys written\n";
}
foreach (array_keys($keys) as $k) {
    if (in_array('--missing', $argv, true) && isset($dict[$k])) continue;
    echo $k, "\n";
}
fwrite(STDERR, count($keys) . " keys, " . count(array_diff_key($keys, $dict)) . " missing in zh.php\n");
